### ISSUE TITLE
Window is not closed when running in daemon mode in bspwm

### ISSUE THREAD

**Issue by TheZoq2** [gmc-holle/xfdashboard#156]
The program works fine in non dameon mode but the slight delay when starting is mildly annoying so I want to try running it in daemon mode.

Starting it works fine the first time, but starting programs or switching to other windows does not close the dashboard, instead it takes it out of fullscreen into a tiled window. Clicking windows or apps does nothting and trying to toggle it with `xfdashboard -t` does nothing. 

However, switching to other workspaces works, (though it still doesn't close the dashboard window).

**Comment by gmc-holle** [comment]
Weird :( But it sounds like the issue #147 with marco (metacity fork) window manager of MATE. I still have no idea but the cause of this problem may be. :(

Can you confirm that you are affected from the same issues as described at issue #147 before I mark this one as a duplicate? Thanks

**Comment by TheZoq2** [comment]
Thats what I suspected as well, but I tested it now and it doesn't print the same thing as reported in #147. Mine only prints 

```
(xfdashboard:29768): xfdashboard-WARNING **: Keep window fullscreen on primary monitor because window manager does not support _NET_WM_FULLSCREEN_MONITORS.
```

I can try installing MATE and trying it there later today if you think it will help

**Comment by gmc-holle** [comment]
Thanks, but I could already reproduce the problem with MATE's default window manager. As said I have no solution right now :(

The message printed with your window manager is not as bad as it might sound. It just tells you that spanning a window across all connected monitors in fullscreen is not supported by your environment. So just the primary monitor is used. It was well tested but - as usual - only on xfce running xfwm4 window manager.

What version of xfdashboard is installed? Was it installed from distro repository or a 3rd party repository or self-compiled from source? Which xfdashboard/clutter backend was in use (if xfdashboard version 0.7.3 or higher)?

If you don't know which backend is used then run xfdashboard with the environment variable `XFDASHBOARD_DEBUG` set to `XfdashboardWindowTrackerBackendX11,XfdashboardWindowTrackerBackendGDK`. xfdashboard should not run in daemon mode at this time (I think it will not because of this issue ;) )

```
XFDASHBOARD_DEBUG=XfdashboardWindowTrackerBackendX11,XfdashboardWindowTrackerBackendGDK xfdashboard
```

If it is compiled from source could you paste the last output of the configure script? It should look similiar to this:

```
Build configuration:
  Package:          xfdashboard
  Version:          0.7.5git.8973b5a
  Library version:  700:5:700

Compiler options:
  Compiler flags:   -g -O2  -DXFCE_DISABLE_DEPRECATED -Wall -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wold-style-definition -Wdeclaration-after-statement -Wmissing-declarations -Wmissing-noreturn -Wshadow -Wpointer-arith -Wcast-align -Wformat -Wformat-security -Wformat-y2k -Winit-self -Wmissing-include-dirs -Wundef -Wnested-externs -fstack-protector -Wredundant-decls -g 
  Debug level:      yes
  Debug flags:      -DXFDASHBOARD_ENABLE_DEBUG

Library versions used:
  libwnck:          3.20.1
  clutter:          1.26.2
  cogl:             1.26.2
  gtk+:             3.22.16
  glib:             2.50.3
  gio:              2.50.3
  gio-unix:         2.50.3
  garcon:           0.6.1
  libxfce4ui:       4.13.3
  libxfce4util:     4.13.1
  libxconf:         4.13.3

Tools used:
  glib-genmarshal:  glib-genmarshal
  glib-mkenums:     glib-mkenums

Features enabled:
  Backends:         x11 gdk
  XComposite:       yes
  XDamage:          yes
  Xinerama:         yes

Now type "make" to compile.
```

**Comment by TheZoq2** [comment]
Looks like it's using the x11 backend:
```
xfdashboard-Message: [         +0.0000]:[XfdashboardWindowTrackerBackendX11@0x5642d3993620]:[WINDOWS]:x11/window-tracker-backend-x11.c:745: Initializing X11 window tracker backend
xfdashboard-Message: [         +0.0000]:[XfdashboardWindowTrackerBackendX11@0x5642d3993620]:[WINDOWS]:window-tracker-backend.c:142: Create window tracker backend of type XfdashboardWindowTrackerBackendX11 with ID 'x11' for clutter backend 'x11'
```

And this is the output of ./configure:
```

**Comment by gmc-holle** [comment]
That's pretty much the same environment as mine and sadly it was expected to be :( So I still have no idea what may cause this problem.

Just a shot in the dark. Could you apply this patch and check if it gets better?

```
diff --git a/libxfdashboard/x11/window-tracker-x11.c b/libxfdashboard/x11/window-tracker-x11.c
index 51ca473..a61061b 100644
--- a/libxfdashboard/x11/window-tracker-x11.c
+++ b/libxfdashboard/x11/window-tracker-x11.c
@@ -1960,6 +1960,9 @@ guint32 xfdashboard_window_tracker_x11_get_time(void)
        guint32                                 timestamp;
        GdkDisplay                              *display;
 
+       /* Test for issue GH #156 */
+       return(CLUTTER_CURRENT_TIME);
+
        /* We don't use clutter_get_current_event_time as it can return
         * a too old timestamp if there is no current event.
         */
```

You will get lots of warnings in your console or log after this patch is applied. They look like this:

```
(xfdashboard:3550): Wnck-WARNING **: Received a timestamp of 0; window activation may not function properly.
```

**Comment by TheZoq2** [comment]
I tried it and it doesn't seem to have helped.

I also get this printed to console when I run it in daemon mode which I haven't seen before. Though it might also be related to the changes I made in #157.

(xfdashboard:26535): Wnck-WARNING **: Received a timestamp of 0; window activation may not function properly.
```
(xfdashboard:28794): GLib-GObject-CRITICAL **: g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed
```

**Comment by gmc-holle** [comment]
Ok, further shots in the dark as it seems that bspwm checks the source indication and denies some of xfdashboard requests to the window manager.

Could you apply this patch and test again?

```
diff --git a/libxfdashboard/x11/window-tracker-x11.c b/libxfdashboard/x11/window-tracker-x11.c
index 51ca473..156d1bd 100644
--- a/libxfdashboard/x11/window-tracker-x11.c
+++ b/libxfdashboard/x11/window-tracker-x11.c
@@ -1854,7 +1854,7 @@ void xfdashboard_window_tracker_x11_init(XfdashboardWindowTrackerX11 *self)
        priv->supportsMultipleMonitors=FALSE;
 
        /* The very first call to libwnck should be setting the client type */
-       wnck_set_client_type(WNCK_CLIENT_TYPE_PAGER);
+       wnck_set_client_type(WNCK_CLIENT_TYPE_APPLICATION);
 
        /* Connect signals to screen */
        g_signal_connect_swapped(priv->screen,
```

If it still not works, can you revert the patch above? The one with the comment `/* Test for issue GH #156 */`. If it is not applied anymore can you re-apply it in this case?

**Comment by TheZoq2** [comment]
I tried it but it doesn't seem to have made a difference

**Comment by gmc-holle** [comment]
Hmmm ... and how does the experimental marked GDK backend work for you? To start xfdashboard in daemon mode with GDK backend and debug message use this command in your terminal:

```
XFDASHBOARD_BACKEND=gdk XFDASHBOARD_DEBUG=XfdashboardWindowTrackerBackendX11,XfdashboardWindowTrackerBackendGDK xfdashboard -d
```

I'm afraid the results aren't better but please give it a try.

**Comment by TheZoq2** [comment]
That segfaults as soon as the program starts

**Comment by gmc-holle** [comment]
Ok .... **this** was unexpected :( Could you provide a backtrace with the gdb debugger from this crash?

**Comment by TheZoq2** [comment]
Sure, here is the backtrace

```
#0  0x00007ffff65dc812 in  () at /usr/lib/libgdk-3.so.0
#1  0x00007ffff661489f in gdk_x11_window_get_xid () at /usr/lib/libgdk-3.so.0
#2  0x00007ffff7b7a7c0 in _xfdashboard_window_tracker_backend_gdk_window_tracker_backend_get_stage_from_window (inBackend=<optimized out>, inStageWindow=<optimized out>) at gdk/window-tracker-backend-gdk.c:478
#3  0x00007ffff7b5eb97 in xfdashboard_window_tracker_window_get_stage (self=0x55555602dc30) at window-tracker-window.c:782
#4  0x00007ffff7b5ec42 in xfdashboard_window_tracker_window_is_stage (self=self@entry=0x55555602dc30) at window-tracker-window.c:742
#5  0x00007ffff7b14749 in _xfdashboard_live_workspace_is_visible_window (self=self@entry=0x55555601dd70, inWindow=inWindow@entry=0x55555602dc30) at live-workspace.c:119
#6  0x00007ffff7b14a44 in _xfdashboard_live_workspace_on_window_opened (self=0x55555601dd70, inWindow=0x55555602dc30, inUserData=<optimized out>) at live-workspace.c:382
#7  0x00007ffff6354ead in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff63674ae in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff636fc85 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff6370b78 in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#11 0x00007ffff6357e59 in g_cclosure_marshal_VOID__OBJECTv () at /usr/lib/libgobject-2.0.so.0
#12 0x00007ffff63550e6 in  () at /usr/lib/libgobject-2.0.so.0
#13 0x00007ffff636ff6f in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#14 0x00007ffff637069f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff582a586 in  () at /usr/lib/libwnck-3.so.0
#16 0x00007ffff5828e06 in  () at /usr/lib/libwnck-3.so.0
#17 0x00007ffff582a33f in  () at /usr/lib/libwnck-3.so.0
#18 0x00007ffff582a3d1 in  () at /usr/lib/libwnck-3.so.0
#19 0x00007ffff607c8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#20 0x00007ffff607cc88 in  () at /usr/lib/libglib-2.0.so.0
#21 0x00007ffff607cd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff692d72d in g_application_run () at /usr/lib/libgio-2.0.so.0
#23 0x00005555555553b2 in main (argc=<optimized out>, argv=<optimized out>) at main.c:252
```

**Comment by gmc-holle** [comment]
Could you retry the tests with the GDK backend with latest git commit 4ca56f59dd47bbea6a9c6c351ce0d576206348dd?

**Comment by TheZoq2** [comment]
Progress, but it still crashes. This time with the following messages:

```
(lt-xfdashboard:32484): GLib-GObject-CRITICAL **: g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed
xfdashboard-Message: [         +0.0655]:[XfdashboardWindowTrackerBackendGDK@0x56000e646530]:[WINDOWS]:gdk/window-tracker-backend-gdk.c:483: Could not get GDK window from stage XfdashboardStage@0x56000e7a46a0
xfdashboard-Message: [         +0.0655]:[XfdashboardWindowTrackerBackendGDK@0x56000e646530]:[WINDOWS]:gdk/window-tracker-backend-gdk.c:483: Could not get GDK window from stage XfdashboardStage@0x56000e7a46a0

(lt-xfdashboard:32484): GLib-GObject-CRITICAL **: g_cclosure_marshal_VOID__VOID: assertion 'n_param_values == 1' failed

(lt-xfdashboard:32484): Gdk-ERROR **: The program 'lt-xfdashboard' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadPixmap (invalid Pixmap parameter)'.
  (Details: serial 997 error_code 4 request_code 54 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
zsh: trace trap (core dumped)  XFDASHBOARD_BACKEND=gdk XFDASHBOARD_DEBUG= ./xfdashboard/xfdashboard -d
```

Here is a backtrace again if it helps
```
0x00007ffff6082411 in ?? () from /usr/lib/libglib-2.0.so.0
>>> back
#0  0x00007ffff6082411 in  () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff6084a61 in g_log_writer_default () at /usr/lib/libglib-2.0.so.0
#2  0x00007ffff6082fae in g_log_structured_array () at /usr/lib/libglib-2.0.so.0
#3  0x00007ffff60832a7 in g_log_structured () at /usr/lib/libglib-2.0.so.0
#4  0x00007ffff65f6f64 in  () at /usr/lib/libgdk-3.so.0
#5  0x00007ffff6604845 in  () at /usr/lib/libgdk-3.so.0
#6  0x00007ffff17916ed in _XError () at /usr/lib/libX11.so.6
#7  0x00007ffff178e617 in  () at /usr/lib/libX11.so.6
#8  0x00007ffff178e6d5 in  () at /usr/lib/libX11.so.6
#9  0x00007ffff178f5e8 in _XReply () at /usr/lib/libX11.so.6
#10 0x00007ffff177579e in XGetWindowProperty () at /usr/lib/libX11.so.6
#11 0x00007ffff58450ab in  () at /usr/lib/libwnck-3.so.0
#12 0x00007ffff5829a2a in  () at /usr/lib/libwnck-3.so.0
#13 0x00007ffff582a34b in  () at /usr/lib/libwnck-3.so.0
#14 0x00007ffff582a3d1 in  () at /usr/lib/libwnck-3.so.0
#15 0x00007ffff607c8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007ffff607cc88 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007ffff607cd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007ffff692d72d in g_application_run () at /usr/lib/libgio-2.0.so.0
#19 0x00005555555553b2 in main (argc=<optimized out>, argv=<optimized out>) at main.c:252
```

**Comment by gmc-holle** [comment]
The bad at this backtrace is that no function of xfdashboard is involved except for the main entry function of course. :(

I don't know what is soooo different between xfwm4 and other window managers. To be honest I only use and check against xfwm4 but I have never seen these problems :/

If you (or anyone else) has any idea or hint ... please tell me.

**Comment by gmc-holle** [comment]
Looks like xfdashboard is working with bspwm now as mentioned in issue #179 -> closed
