### ISSUE TITLE
xfdashboard-settings crashes

### ISSUE THREAD

**Issue by gmc-holle** [gmc-holle/xfdashboard#62]
xfdashboard-settings crashed with the following gdb output:

```
GNU gdb (GDB) 7.8.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later 
<http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from xfdashboard-settings...(no debugging symbols 
found)...done.
(gdb) run
Starting program: /usr/bin/xfdashboard-settings
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

** (xfdashboard-settings:31817): WARNING **: Couldn't register with 
accessibility bus: Did not receive a reply. Possible causes include: the 
remote application did not send a reply, the message bus security policy 
blocked the reply, the reply timeout expired, or the network connection 
was broken.
[New Thread 0x7fffe9eb8700 (LWP 31821)]

(xfdashboard-settings:31817): GLib-CRITICAL **: 
g_hash_table_remove_internal: assertion 'hash_table != NULL' failed

(xfdashboard-settings:31817): GLib-WARNING **: corrupted double-linked 
list detected

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff638c933 in g_list_remove_link () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff638c933 in g_list_remove_link () from 
/usr/lib/libglib-2.0.so.0
#1  0x00007ffff6386ee5 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ffff6386f94 in ?? () from /usr/lib/libglib-2.0.so.0
#3  0x00007ffff63870d4 in ?? () from /usr/lib/libglib-2.0.so.0
#4  0x00007ffff6388fde in g_key_file_free () from /usr/lib/libglib-2.0.so.0
#5  0x000055555555a043 in _xfdashboard_settings_create_builder ()
#6  0x000055555555a464 in xfdashboard_settings_create_dialog ()
#7  0x0000555555557b1f in main ()
```

Library used: GTK 3.14.7

This issue was reported at the xfce user's mailing list.

**Comment by korrode** [comment]
https://github.com/gmc-holle/xfdashboard/commit/896648557d545eb355df159f7003f4e0d5775004

Does indeed fix it :+1:

**Comment by gmc-holle** [comment]
Oh ... thanks for your feedback. I was just asking at the mailing list ;)

Closing bug but it looks like I should release an new version to render the new settings application usable. :(
